/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import static org.hamcrest.Matchers.*;

public class CalculatorTest {
    public CalculatorTest() {
    }

    @Test
    public void 正常系テスト() {
        Calculator calc = new Calculator();
        assertThat(calc.add(1, 2), is(3)); // 1+2は3となるか？
        assertThat(calc.add(5, 2), is(7)); // 5+2は7となるか？
    }

    @Test
    public void 異常系テスト_プラス値境界値() {
        Calculator calc = new Calculator();
        assertThat(calc.add(
            Integer.MAX_VALUE, 0),
            is(Integer.MAX_VALUE)); // 整数最大値プラスゼロは演算可能

        try {
            calc.add(Integer.MAX_VALUE, 1); // 整数最大値プラス1は桁あふれ
        } catch(ArithmeticException e) {
            assertTrue("overflow".equals(e.getMessage()));
            return ;
        }
        fail();
    }

    @Test
    public void 異常系テスト_マイナス値境界値() {
        Calculator calc = new Calculator();

        try {
            calc.add(Integer.MIN_VALUE, -1); // 整数最小値プラス-1は桁あふれ
        } catch(ArithmeticException e) {
            assertTrue("overflow".equals(e.getMessage()));
            return ;
        }
        fail();
    }
}