/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'k_watanabe' at '16/12/21 16:39' with Gradle 3.1
 *
 * @author k_watanabe, @date 16/12/21 16:39
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
