/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tools.dockingpane;

import org.junit.Test;

public class AppTest {
    @Test public void testAppHasAGreeting() {
    }
}
